import { ExperienceRole } from './Experience.interface';

export const EXPERIENCE_SECTION_HEADER = {
  eyebrow: 'Career Progression',
  titleStart: 'Professional',
  titleHighlight: 'Work Experience',
  subtitle:
    'A track record of shipping enterprise-grade B2B SaaS platforms, high-performance MERN applications, and modern AI-augmented engineering workflows.',
};

export const EXPERIENCE_ROLES: ExperienceRole[] = [
  {
    id: 'dbiz-ai',
    company: 'Dbiz.ai',
    role: 'Senior Software Engineer',
    location: 'Bengaluru, India',
    period: 'May 2025 – Present',
    startDateIso: '2025-05-01',
    isCurrent: true,
    clientProject:
      'Enterprise Client: RingCentral ACE (B2B SaaS Contact Center)',
    highlights: [
      'Develop and maintain frontend modules for RingCentral ACE, an enterprise B2B SaaS contact center platform, as a Senior React.js and TypeScript developer.',
      'Implemented WCAG accessibility standards across the product, delivering inclusive, compliant user experiences for enterprise clients.',
      'Applied advanced TypeScript patterns and strict typing practices across the codebase, improving type safety and long-term maintainability.',
      "Conduct code reviews on junior developers' merge requests, enforcing coding standards and frontend best practices.",
      'Integrated Jira and internal UI component libraries into the development environment via Cursor MCP, giving the team in-editor access to project tasks and design system components.',
      'Built automation workflows using OpenAI Codex for bulk Jira ticket updates and specification-driven code generation, reducing repetitive manual effort.',
      'Collaborate in an Agile team using Jira for sprint planning, estimation, and task tracking.',
    ],
    technologies: [
      'React.js',
      'TypeScript',
      'Redux Toolkit',
      'React Query',
      'WCAG 2.1',
      'REST APIs',
      'SSO & RBAC',
      'Cursor MCP',
      'OpenAI Codex',
      'Jira / Agile',
    ],
  },
  {
    id: 'censanext',
    company: 'Censanext',
    role: 'React Developer',
    location: 'Chennai, India',
    period: 'Nov 2022 – May 2025',
    startDateIso: '2022-11-01',
    endDateIso: '2025-05-01',
    isCurrent: false,
    clientProject: 'Enterprise MERN & SaaS Product Engineering',
    highlights: [
      'Developed and optimized 5+ MERN stack applications, improving application performance by approximately 30%.',
      'Integrated REST APIs across React.js frontends to enable reliable frontend-backend communication and consistent data flow.',
      'Partnered with cross-functional teams to define application architecture and prioritize feature delivery.',
      'Maintained code quality through peer code reviews, unit testing (Jest & React Testing Library), and systematic debugging of production issues.',
      'Implemented GitLab CI/CD pipelines to automate build and deployment workflows.',
    ],
    technologies: [
      'React.js',
      'Redux',
      'JavaScript (ES6+)',
      'Node.js',
      'Express.js',
      'MongoDB',
      'REST APIs',
      'Jest & RTL',
      'GitLab CI/CD',
    ],
  },
  // {
  //   id: 'be-practical',
  //   company: 'Be Practical Tech Solutions',
  //   role: 'MERN Stack Developer Intern & Trainee',
  //   location: 'Bengaluru, India',
  //   period: '2022 (6 Months)',
  //   isCurrent: false,
  //   clientProject: 'Full Stack MERN Development & Responsive Web Architecture',
  //   highlights: [
  //     'Completed intensive 6-month MERN Full Stack internship and hands-on engineering program.',
  //     'Built full-stack multi-vendor e-commerce applications, RESTful APIs with Node.js/Express/MongoDB, and responsive UI architectures.',
  //   ],
  //   technologies: [
  //     'React.js',
  //     'Node.js',
  //     'Express.js',
  //     'MongoDB',
  //     'HTML5 & CSS3',
  //     'Bootstrap',
  //     'Git',
  //   ],
  // },
];
